apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  type: LoadBalancer   # or NodePort, depending on your need
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 80          # Cluster IP service port
      targetPort: 8080  # Container port (must match your Deployment)
      nodePort: 31200   # External port (only used if type=NodePort/LoadBalancer)
    
